# render.yaml
services:
  - type: web
    name: nifty-oc-live
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app" # Use gunicorn to run the Flask app
    plan: free # Start with a free tier
