services:
  - type: web
    name: nse-dashboard
    env: python
    pythonVersion: 3.12.7  # ADD THIS LINE
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
